# Generated by Django 3.1 on 2022-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
